version: '3.7'

services:
  devcontainer:
    image: acme/orderservice-dev-container:0.1
    build: .
    container_name: orderservice-dev-container
    hostname: orderservice-dev.local
    working_dir: /src
    volumes:
       - ..:/src
       # Allow AWS CLI and other tools to read an AWS profile
       - ~/.aws:/home/node/.aws
    command: sleep infinity
    ports:
      - 3000:3000
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webexplorer
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: