version: '3.7'

services:
  devcontainer:
    image: acme/orderservice-dev-container:0.1
    build: .
    container_name: orderservice-dev-container
    hostname: orderservice-dev.local
    working_dir: /src
    volumes:
       - ..:/src
       # Allow AWS CLI and other tools to read an AWS profile
       - ~/.aws:/home/node/.aws
    command: sleep infinity
    ports:
      - 3000:3000
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1